import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from feature_engine.imputation import ArbitraryNumberImputer
from feature_engine.transformation import PowerTransformer
train_df = pd.read_csv('../data/house-prices/train.csv')
test_df = pd.read_csv('../data/house-prices/test.csv')
X_train = train_df.drop(['Id', 'SalePrice'], axis=1)
y_train = train_df['SalePrice']
X_test = test_df.drop(['Id'], axis=1)
print('X_train :', X_train.shape)
print('X_test :', X_test.shape)
et_transformer = PowerTransformer(variables=['LotArea', 'GrLivArea'], exp=0.5)
et_transformer.fit(X_train)
train_t = et_transformer.transform(X_train)
test_t = et_transformer.transform(X_test)
X_train['GrLivArea'].hist(bins=50)
plt.title('Variable before transformation')
plt.xlabel('GrLivArea')
train_t['GrLivArea'].hist(bins=50)
plt.title('Transformed variable')
plt.xlabel('GrLivArea')
X_train['LotArea'].hist(bins=50)
plt.title('Variable before transformation')
plt.xlabel('LotArea')
train_t['LotArea'].hist(bins=50)
plt.title('Variable before transformation')
plt.xlabel('LotArea')
train_orig = et_transformer.inverse_transform(train_t)
test_orig = et_transformer.inverse_transform(test_t)
train_orig['LotArea'].hist(bins=50)
train_orig['GrLivArea'].hist(bins=50)
arbitrary_imputer = ArbitraryNumberImputer()
arbitrary_imputer.fit(X_train)
train_t = arbitrary_imputer.transform(X_train)
test_t = arbitrary_imputer.transform(X_test)
et = PowerTransformer(exp=2, variables=None)
et.fit(train_t)
et.variables_
train_t['GrLivArea'].hist(bins=50)
train_t = et.transform(train_t)
test_t = et.transform(test_t)
train_t['GrLivArea'].hist(bins=50)
train_orig = et_transformer.inverse_transform(train_t)
test_orig = et_transformer.inverse_transform(test_t)
train_orig['LotArea'].hist(bins=50)
train_orig['GrLivArea'].hist(bins=50)
